"use client";

import React, { useState, useEffect, useCallback } from "react";
import Link from "next/link";
import api from "@/lib/api";

const CATEGORIES = [
  "All",
  "Admit Card",
  "Exam Date",
  "Answer Key",
  "Result",
  "Recruitment",
  "Syllabus",
  "Cutoff",
  "General",
];

const SECTORS = [
  "All",
  "Central Govt",
  "SSC",
  "Banking & Insurance",
  "Railways",
  "Defence & Police",
  "Teaching",
  "Engineering & PSU",
  "Civil Services / UPSC",
  "State Govt",
];

const STATES = [
  "All",
  "All India",
  "Delhi",
  "Uttar Pradesh",
  "Bihar",
  "Rajasthan",
  "Madhya Pradesh",
  "Haryana",
  "Maharashtra",
  "West Bengal",
];

export default function AdminArticlesPage() {
  const [articles, setArticles] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  // Filters
  const [search, setSearch] = useState("");
  const [category, setCategory] = useState("All");
  const [sector, setSector] = useState("All");
  const [state, setState] = useState("All");
  const [status, setStatus] = useState("");

  // Auto Ingest Sync State
  const [syncing, setSyncing] = useState(false);
  const [syncResult, setSyncResult] = useState(null);

  // Delete State
  const [deletingId, setDeletingId] = useState(null);
  const [deleteConfirm, setDeleteConfirm] = useState(null);

  const fetchArticles = useCallback(async () => {
    try {
      setLoading(true);
      setError(null);

      const params = {};
      if (category && category !== "All") params.category = category;
      if (sector && sector !== "All") params.sector = sector;
      if (state && state !== "All") params.state = state;
      if (status) params.status = status;
      if (search.trim()) params.q = search.trim();

      const res = await api.get("/api/admin/articles", { params });
      if (res.data && res.data.articles) {
        setArticles(res.data.articles);
      }
    } catch (err) {
      console.error("Failed to load articles:", err);
      setError(err.response?.data?.message || "Failed to load articles");
    } finally {
      setLoading(false);
    }
  }, [category, sector, state, status, search]);

  useEffect(() => {
    fetchArticles();
  }, [fetchArticles]);

  const handleTriggerSync = async () => {
    try {
      setSyncing(true);
      setSyncResult(null);
      const res = await api.post("/api/admin/articles/sync");
      if (res.data && res.data.stats) {
        setSyncResult(res.data.stats);
        await fetchArticles();
      }
    } catch (err) {
      alert(err.response?.data?.message || "Sync failed. Check console.");
    } finally {
      setSyncing(false);
    }
  };

  const handleDelete = async (id) => {
    try {
      setDeletingId(id);
      await api.delete(`/api/admin/articles/${id}`);
      setArticles((prev) => prev.filter((a) => a._id !== id));
      setDeleteConfirm(null);
    } catch (err) {
      alert(err.response?.data?.message || "Failed to delete article");
    } finally {
      setDeletingId(null);
    }
  };

  // Stats
  const totalArticles = articles.length;
  const publishedCount = articles.filter((a) => a.status === "Published").length;
  const draftCount = articles.filter((a) => a.status === "Draft").length;
  const autoCount = articles.filter((a) => a.isAutoGenerated).length;

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-6">
      {/* Top Banner & Header */}
      <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4 bg-white p-6 rounded-3xl shadow-sm border border-slate-200">
        <div>
          <div className="flex items-center gap-2">
            <span className="text-2xl">📰</span>
            <h1 className="text-2xl font-black text-slate-900">
              Exam Articles & News CMS
            </h1>
          </div>
          <p className="text-xs sm:text-sm text-slate-500 mt-1">
            Auto-ingest real-time exam alerts or publish custom guides, admit cards, and results.
          </p>
        </div>

        <div className="flex flex-wrap items-center gap-2.5">
          {/* One-Click Auto Ingest Button */}
          <button
            onClick={handleTriggerSync}
            disabled={syncing}
            className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl bg-gradient-to-r from-emerald-600 to-teal-600 hover:from-emerald-700 hover:to-teal-700 text-white font-bold text-xs shadow-sm transition disabled:opacity-50 cursor-pointer"
          >
            {syncing ? (
              <>
                <div className="h-3.5 w-3.5 animate-spin rounded-full border-2 border-white border-t-transparent" />
                <span>Crawling Live Sites...</span>
              </>
            ) : (
              <>
                <span>⚡</span>
                <span>Auto-Ingest Live Updates</span>
              </>
            )}
          </button>

          <button
            onClick={fetchArticles}
            className="px-3.5 py-2.5 rounded-xl text-xs font-semibold text-slate-600 bg-slate-100 hover:bg-slate-200 transition"
          >
            🔄 Refresh
          </button>

          <Link
            href="/admin/articles/new"
            className="inline-flex items-center gap-1.5 px-4 py-2.5 rounded-xl bg-blue-600 hover:bg-blue-700 text-white font-bold text-xs shadow-sm transition"
          >
            <span>+ Write Article</span>
          </Link>
        </div>
      </div>

      {/* Sync Result Notice Banner */}
      {syncResult && (
        <div className="p-4 rounded-2xl bg-emerald-50 border border-emerald-200 text-emerald-900 text-xs flex items-center justify-between shadow-xs">
          <div className="flex items-center gap-3">
            <span className="text-2xl">🚀</span>
            <div>
              <strong className="block text-emerald-950 font-extrabold">
                Auto-Crawler Sync Complete!
              </strong>
              <span>
                Scanned {syncResult.scanned} candidate links from{" "}
                {syncResult.sourcesChecked.join(", ")} |{" "}
                <span className="font-bold text-emerald-800">
                  +{syncResult.created} new article(s) published
                </span>{" "}
                | {syncResult.duplicatesSkipped} duplicates intelligently skipped.
              </span>
            </div>
          </div>
          <button
            onClick={() => setSyncResult(null)}
            className="text-emerald-700 hover:text-emerald-950 text-base font-bold p-1"
          >
            ✕
          </button>
        </div>
      )}

      {/* Metrics Row */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
        <div className="bg-white p-4 rounded-2xl border border-slate-200 shadow-xs">
          <span className="text-xs font-semibold text-slate-500">Total in DB</span>
          <p className="text-2xl font-black text-slate-900 mt-1">{totalArticles}</p>
        </div>
        <div className="bg-white p-4 rounded-2xl border border-emerald-200 bg-emerald-50/20 shadow-xs">
          <span className="text-xs font-semibold text-emerald-700">Published</span>
          <p className="text-2xl font-black text-emerald-600 mt-1">{publishedCount}</p>
        </div>
        <div className="bg-white p-4 rounded-2xl border border-amber-200 bg-amber-50/20 shadow-xs">
          <span className="text-xs font-semibold text-amber-700">Drafts</span>
          <p className="text-2xl font-black text-amber-600 mt-1">{draftCount}</p>
        </div>
        <div className="bg-white p-4 rounded-2xl border border-teal-200 bg-teal-50/20 shadow-xs">
          <span className="text-xs font-semibold text-teal-700">⚡ Auto-Ingested</span>
          <p className="text-2xl font-black text-teal-600 mt-1">{autoCount}</p>
        </div>
      </div>

      {/* Filter and Search Bar */}
      <div className="bg-white p-4 rounded-2xl border border-slate-200 shadow-xs flex flex-col md:flex-row gap-3 items-stretch md:items-center justify-between">
        <div className="flex-1 relative">
          <span className="absolute inset-y-0 left-0 flex items-center pl-3 text-slate-400 text-sm">
            🔍
          </span>
          <input
            type="text"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            placeholder="Search articles by title, slug, sector, or organization..."
            className="w-full pl-9 pr-3 py-2 text-xs rounded-xl border border-slate-200 bg-slate-50 focus:bg-white focus:outline-none focus:ring-2 focus:ring-blue-600/30 font-medium"
          />
        </div>

        <div className="flex flex-wrap items-center gap-2">
          {/* Sector filter */}
          <select
            value={sector}
            onChange={(e) => setSector(e.target.value)}
            className="text-xs py-2 px-3 rounded-xl border border-slate-200 bg-white focus:outline-none focus:ring-2 focus:ring-blue-600/30 font-semibold"
          >
            {SECTORS.map((sec) => (
              <option key={sec} value={sec}>
                Sector: {sec}
              </option>
            ))}
          </select>

          {/* State filter */}
          <select
            value={state}
            onChange={(e) => setState(e.target.value)}
            className="text-xs py-2 px-3 rounded-xl border border-slate-200 bg-white focus:outline-none focus:ring-2 focus:ring-blue-600/30 font-semibold"
          >
            {STATES.map((st) => (
              <option key={st} value={st}>
                State: {st}
              </option>
            ))}
          </select>

          {/* Category filter */}
          <select
            value={category}
            onChange={(e) => setCategory(e.target.value)}
            className="text-xs py-2 px-3 rounded-xl border border-slate-200 bg-white focus:outline-none focus:ring-2 focus:ring-blue-600/30 font-semibold"
          >
            {CATEGORIES.map((cat) => (
              <option key={cat} value={cat}>
                Type: {cat}
              </option>
            ))}
          </select>
        </div>
      </div>

      {/* Articles Table */}
      <div className="bg-white rounded-3xl border border-slate-200 shadow-xs overflow-hidden">
        {loading ? (
          <div className="py-20 text-center text-slate-500">
            <div className="inline-block h-7 w-7 animate-spin rounded-full border-3 border-blue-600 border-t-transparent mb-3" />
            <p className="text-xs font-semibold">Loading articles from database...</p>
          </div>
        ) : error ? (
          <div className="py-12 text-center text-red-600 space-y-2">
            <p className="text-sm font-bold">⚠️ {error}</p>
            <button
              onClick={fetchArticles}
              className="px-4 py-1.5 text-xs bg-slate-100 hover:bg-slate-200 rounded-lg font-semibold"
            >
              Try Again
            </button>
          </div>
        ) : articles.length === 0 ? (
          <div className="py-16 text-center text-slate-500 space-y-3">
            <span className="text-4xl block">📝</span>
            <p className="text-sm font-semibold text-slate-700">No articles found</p>
            <p className="text-xs text-slate-400">
              Run the auto-ingest crawler or create a custom article.
            </p>
            <div className="flex items-center justify-center gap-3 pt-2">
              <button
                onClick={handleTriggerSync}
                className="px-4 py-2 bg-emerald-600 text-white rounded-xl text-xs font-bold hover:bg-emerald-700 transition cursor-pointer"
              >
                ⚡ Run Auto-Ingest Now
              </button>
              <Link
                href="/admin/articles/new"
                className="px-4 py-2 bg-blue-600 text-white rounded-xl text-xs font-bold hover:bg-blue-700 transition"
              >
                + Write Custom Article
              </Link>
            </div>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse text-xs">
              <thead>
                <tr className="bg-slate-50 border-b border-slate-200 text-slate-600 font-bold uppercase tracking-wider text-[11px]">
                  <th className="py-3.5 px-4">Article Title & Sector</th>
                  <th className="py-3.5 px-4">Category</th>
                  <th className="py-3.5 px-4">State</th>
                  <th className="py-3.5 px-4">Status</th>
                  <th className="py-3.5 px-4">Published (IST)</th>
                  <th className="py-3.5 px-4 text-right">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100">
                {articles.map((item) => (
                  <tr key={item._id} className="hover:bg-slate-50/60 transition">
                    <td className="py-3.5 px-4 max-w-sm">
                      <div className="font-bold text-slate-900 line-clamp-1">
                        {item.title}
                      </div>
                      <div className="flex items-center gap-2 mt-0.5">
                        <span className="text-[10px] text-blue-600 font-bold">
                          🏛️ {item.sector || "Central Govt"}
                        </span>
                        {item.isAutoGenerated && (
                          <span className="text-[9px] font-bold text-teal-700 bg-teal-50 px-1.5 py-0.5 rounded border border-teal-200/50">
                            ⚡ Auto-Crawled
                          </span>
                        )}
                      </div>
                    </td>

                    <td className="py-3.5 px-4">
                      <span className="inline-flex items-center px-2 py-0.5 rounded-md text-[10px] font-bold bg-slate-100 text-slate-700 border border-slate-200">
                        {item.category}
                      </span>
                    </td>

                    <td className="py-3.5 px-4">
                      <span className="inline-flex items-center px-2 py-0.5 rounded-md text-[10px] font-medium bg-emerald-50 text-emerald-800 border border-emerald-200/60">
                        {item.state || "All India"}
                      </span>
                    </td>

                    <td className="py-3.5 px-4">
                      <span
                        className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-[10px] font-extrabold ${
                          item.status === "Published"
                            ? "bg-emerald-100 text-emerald-800 border border-emerald-200"
                            : "bg-amber-100 text-amber-800 border border-amber-200"
                        }`}
                      >
                        {item.status === "Published" ? "● Live" : "○ Draft"}
                      </span>
                    </td>

                    <td className="py-3.5 px-4 text-slate-500 text-[11px] whitespace-nowrap">
                      {item.publishDate ? (
                        <div>
                          <div className="font-semibold text-slate-700">
                            {new Date(item.publishDate)
                              .toLocaleString("en-IN", {
                                timeZone: "Asia/Kolkata",
                                day: "numeric",
                                month: "short",
                                year: "numeric",
                                hour: "2-digit",
                                minute: "2-digit",
                                hour12: true,
                              })
                              .replace(/\b(am|pm)\b/i, (m) => m.toUpperCase())}{" "}
                            IST
                          </div>
                        </div>
                      ) : (
                        "—"
                      )}
                    </td>

                    <td className="py-3.5 px-4 text-right">
                      <div className="flex items-center justify-end gap-2">
                        {/* Live Link */}
                        <Link
                          href={`/news/${item.slug}`}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="px-2.5 py-1 rounded-md text-[11px] font-semibold text-blue-600 hover:bg-blue-50 border border-blue-200 transition"
                          title="View on live website"
                        >
                          Live ↗
                        </Link>

                        {/* Edit Button */}
                        <Link
                          href={`/admin/articles/edit/${item._id}`}
                          className="px-2.5 py-1 rounded-md text-[11px] font-semibold text-indigo-600 hover:bg-indigo-50 border border-indigo-200 transition"
                        >
                          Edit ✎
                        </Link>

                        {/* Delete Button */}
                        <button
                          onClick={() => setDeleteConfirm(item)}
                          className="px-2.5 py-1 rounded-md text-[11px] font-semibold text-red-600 hover:bg-red-50 border border-red-200 transition cursor-pointer"
                        >
                          Delete
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* Delete Confirmation Modal */}
      {deleteConfirm && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/50 backdrop-blur-xs p-4">
          <div className="bg-white rounded-3xl shadow-xl max-w-md w-full p-6 space-y-4 border border-slate-200">
            <h3 className="text-base font-bold text-slate-900">
              Confirm Article Deletion
            </h3>
            <p className="text-xs text-slate-600 leading-relaxed">
              Are you sure you want to delete{" "}
              <span className="font-bold text-slate-900">
                &ldquo;{deleteConfirm.title}&rdquo;
              </span>
              ?
            </p>

            <div className="flex items-center justify-end gap-3 pt-2">
              <button
                onClick={() => setDeleteConfirm(null)}
                disabled={deletingId === deleteConfirm._id}
                className="px-4 py-2 text-xs font-semibold text-slate-600 bg-slate-100 hover:bg-slate-200 rounded-xl transition"
              >
                Cancel
              </button>
              <button
                onClick={() => handleDelete(deleteConfirm._id)}
                disabled={deletingId === deleteConfirm._id}
                className="px-4 py-2 text-xs font-bold text-white bg-red-600 hover:bg-red-700 rounded-xl transition shadow-xs"
              >
                {deletingId === deleteConfirm._id ? "Deleting..." : "Yes, Delete Article"}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
