require("dotenv").config({ path: require("path").resolve(__dirname, "../.env") });
const mongoose = require("mongoose");
const Article = require("../src/models/Article");

async function publishArticle() {
  try {
    const mongoUri = process.env.MONGO_URI;
    if (!mongoUri) {
      throw new Error("MONGO_URI not defined in environment");
    }

    console.log("Connecting to MongoDB Atlas...");
    await mongoose.connect(mongoUri);
    console.log("Connected successfully!");

    const slug = "isro-scientist-engineer-sc-exam-date-2026";

    const articleData = {
      title: "ISRO Scientist / Engineer 'SC' Exam Date 2026 Announced: CBT on 19th October, Check Notice at isro.gov.in",
      slug: slug,
      shortTitle: "ISRO Scientist/Engineer 'SC' Exam Date 2026 Out",
      seoTitle: "ISRO Scientist / Engineer SC Exam Date 2026 Announced: CBT on 19 October",
      metaDescription: "Indian Space Research Organisation (ISRO) ICRB has announced the Computer Based Test (CBT) exam date for Scientist/Engineers 'SC' (Advt ISRO:ICRB:03(EMC):2026). Check exam date (19 October 2026), admit card date, and official notice details.",
      category: "Exam Date",
      categorySlug: "exam-date",
      sector: "Engineering & PSU",
      state: "All India",
      topicKey: "isro-scientist-engineer-sc-2026-cbt",
      sourceUrl: "https://www.isro.gov.in/ICRB_Recruitment13.html",
      isAutoGenerated: false,
      status: "Published",
      badge: "📅 Exam Date Announced",
      author: {
        name: "Prayaas Portal Exam Desk",
        role: "Senior Exam Analyst",
        avatar: "/logo.png",
      },
      readingTime: "4 min read",
      publishDate: new Date("2026-09-18T18:00:00+05:30"),
      lastUpdated: new Date(),
      advtNumber: "ISRO:ICRB:03(EMC):2026",
      organization: "Indian Space Research Organisation (ISRO) - ICRB",
      postName: "Scientist / Engineer 'SC'",
      totalVacancies: "Various Posts",
      examDate: "19th October 2026 (Monday)",
      admitCardReleaseDate: "1st Week of October 2026 (Tentative)",
      admitCardLastDate: "19th October 2026",
      officialWebsite: "https://www.isro.gov.in",
      directAdmitCardLink: "https://www.isro.gov.in/ICRB_Recruitment13.html",
      overview: [
        { label: "Conducting Body", value: "Indian Space Research Organisation (ISRO)" },
        { label: "Recruitment Unit", value: "ISRO Centralised Recruitment Board (ICRB)" },
        { label: "Advertisement No.", value: "ISRO:ICRB:03(EMC):2026" },
        { label: "Advertisement Date", value: "27th August 2026" },
        { label: "Post Name", value: "Scientist / Engineer 'SC'" },
        { label: "Online Application Window", value: "27 August 2026 to 16 September 2026" },
        { label: "Application Status", value: "Closed (Submissions completed)" },
        { label: "Computer Based Test (CBT) Date", value: "19th October 2026" },
        { label: "Official Notification Link", value: "isro.gov.in/ICRB_Recruitment13.html" },
        { label: "Headquarters", value: "Bengaluru, Karnataka" },
      ],
      importantDates: [
        { event: "Notification Released", date: "27 August 2026" },
        { event: "Online Applications Closed", date: "16 September 2026" },
        { event: "Exam Date Announcement", date: "18 September 2026" },
        { event: "Admit Card Release Date", date: "Expected by 10 October 2026" },
        { event: "Computer Based Written Test (CBT)", date: "19 October 2026" },
      ],
      loginCredentialsRequired: [
        "Registration / Application Number",
        "Registered Date of Birth (DD-MM-YYYY) or Password",
        "Captcha verification code shown on screen",
      ],
      stepsToDownload: [
        "Visit the official ISRO portal: https://www.isro.gov.in or https://www.isro.gov.in/Careers.html",
        "Navigate to the 'Centralised Recruitment (ICRB)' tab.",
        "Locate Advertisement ISRO:ICRB:03(EMC):2026 for Scientist/Engineer 'SC'.",
        "Click on 'Download Hall Ticket / Admit Card for CBT Exam' link.",
        "Enter your Registration Number and Date of Birth.",
        "Your ISRO ICRB CBT Admit Card will appear on screen; verify your exam venue and shift timings, then save and print 2 copies.",
      ],
      detailsOnAdmitCard: [
        "Candidate Full Name and Roll Number",
        "Photograph and Digital Signature",
        "Advertisement Number: ISRO:ICRB:03(EMC):2026",
        "Discipline / Area of Work (Scientist/Engineer 'SC')",
        "Date of Examination: 19th October 2026",
        "Reporting Time & Gate Closure Time",
        "Complete Examination Centre Name & Address",
        "Exam Day Instructions and CBT Guidelines",
      ],
      documentsToCarry: [
        "Printed copy of ISRO Scientist/Engineer 'SC' CBT Admit Card 2026",
        "Original Government Photo ID Proof (Aadhaar Card, PAN Card, Voter ID, Passport, or Driving License)",
        "Two recent passport-size color photographs matching application submission",
        "Transparent blue/black ballpoint pen",
      ],
      prohibitedItems: [
        "Electronic gadgets, mobile phones, smart watches, Bluetooth devices, and fitness bands",
        "Scientific calculators (unless specified on hall ticket / virtual screen calculator provided)",
        "Notes, loose sheets, log tables, or study guides",
        "Bags, wallets, purses, and edible items inside the exam hall",
      ],
      faqs: [
        {
          question: "When will the ISRO Scientist/Engineer 'SC' CBT 2026 exam be conducted?",
          answer: "The Computer Based Test (CBT) for ISRO Scientist/Engineer 'SC' (Advt No. ISRO:ICRB:03(EMC):2026) is officially scheduled for 19th October 2026.",
        },
        {
          question: "When will the admit card for ISRO ICRB 2026 be released?",
          answer: "The hall tickets are anticipated to be available for download approximately 7 to 10 days before the exam, around the first or second week of October 2026 at isro.gov.in.",
        },
        {
          question: "What was the last date to submit the application form?",
          answer: "The online submission window for Advt ISRO:ICRB:03(EMC):2026 opened on 27th August 2026 and concluded on 16th September 2026.",
        },
        {
          question: "Where can I check the official ISRO exam notice?",
          answer: "Candidates can review the official announcement on the ISRO Careers portal at https://www.isro.gov.in/ICRB_Recruitment13.html.",
        },
      ],
      content: `
        <h2>ISRO Scientist / Engineer 'SC' Exam Date 2026 Announced</h2>
        <p>The <strong>Indian Space Research Organisation (ISRO)</strong> through its Centralised Recruitment Board (ICRB) has officially notified the examination schedule for recruitment to the post of <strong>Scientist/Engineers 'SC'</strong> under Advertisement Number <strong>ISRO:ICRB:03(EMC):2026</strong>.</p>
        
        <p>As per the latest notification released on the official portal (<em>isro.gov.in</em>), the <strong>Computer Based Test (CBT)</strong> will be conducted on <strong>19th October 2026</strong> across designated examination centres in Bengaluru and key metropolitan centers nationwide.</p>

        <h3>Key Highlights of Advertisement ISRO:ICRB:03(EMC):2026</h3>
        <ul>
          <li><strong>Organization:</strong> Indian Space Research Organisation (ISRO)</li>
          <li><strong>Recruitment Unit:</strong> Centralised Recruitment (ICRB)</li>
          <li><strong>Post:</strong> Scientist/Engineers 'SC'</li>
          <li><strong>Advertisement Date:</strong> 27th August 2026</li>
          <li><strong>Last Date for Online Submission:</strong> 16th September 2026</li>
          <li><strong>Date of Conducting CBT:</strong> <strong>19th October 2026</strong></li>
          <li><strong>Status:</strong> Exam Date Announced</li>
        </ul>

        <h3>ISRO ICRB CBT Exam Pattern & Selection Process</h3>
        <p>The selection methodology for Scientist/Engineer 'SC' consists of two main stages:</p>
        <ol>
          <li><strong>Stage 1 (Computer Based Test - CBT):</strong> Objective multiple-choice test testing core engineering fundamentals, discipline knowledge, and analytical aptitude.</li>
          <li><strong>Stage 2 (Interview):</strong> Candidates clearing the screening CBT cutoff will be shortlisted for personal interview rounds at designated ISRO centres. Final selection weightage is strictly aligned with ICRB norms.</li>
        </ol>

        <h3>Admit Card Release Date</h3>
        <p>Candidates who submitted their online applications on or before the closing date (16th September 2026) will be issued electronic hall tickets. The ICRB hall ticket download link will become active tentatively in the <strong>first week of October 2026</strong> at <code>isro.gov.in/Careers.html</code>.</p>
      `,
      tags: [
        "ISRO Scientist SC Exam Date 2026",
        "ISRO ICRB Recruitment 2026",
        "ISRO 03 EMC 2026",
        "Scientist Engineer SC CBT Date",
        "Govt Engineering Jobs 2026",
        "ISRO Admit Card 2026",
      ],
    };

    const updated = await Article.findOneAndUpdate(
      { slug: slug },
      { $set: articleData },
      { upsert: true, new: true, setDefaultsOnInsert: true }
    );

    console.log("Article successfully published to MongoDB!");
    console.log("ID:", updated._id);
    console.log("Title:", updated.title);
    console.log("Slug:", updated.slug);
    console.log("Category:", updated.category);
    console.log("Sector:", updated.sector);
    console.log("Exam Date:", updated.examDate);

    process.exit(0);
  } catch (err) {
    console.error("Failed to publish article:", err);
    process.exit(1);
  }
}

publishArticle();
