"use client";

import React, { useState, useEffect, use } from "react";
import Link from "next/link";
import api from "@/lib/api";
import ArticleClient from "@/app/news/[slug]/ArticleClient";

export default function AdminArticlePreviewPage({ params }) {
  const resolvedParams = use(params);
  const id = resolvedParams.id;

  const [article, setArticle] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [statusUpdating, setStatusUpdating] = useState(false);
  const [actionMessage, setActionMessage] = useState(null);

  useEffect(() => {
    async function fetchArticle() {
      try {
        setLoading(true);
        setError(null);
        const res = await api.get(`/api/admin/articles/${id}`);
        if (res.data && res.data.article) {
          setArticle(res.data.article);
        } else {
          setError("Article not found");
        }
      } catch (err) {
        console.error("Failed to load preview article:", err);
        setError(err.response?.data?.message || "Failed to load article");
      } finally {
        setLoading(false);
      }
    }

    if (id) {
      fetchArticle();
    }
  }, [id]);

  const handleToggleStatus = async (targetStatus) => {
    try {
      setStatusUpdating(true);
      setActionMessage(null);
      const res = await api.patch(`/api/admin/articles/${id}/status`, {
        status: targetStatus,
      });

      if (res.data && res.data.article) {
        setArticle((prev) => ({
          ...prev,
          status: res.data.article.status,
          publishDate: res.data.article.publishDate || prev.publishDate,
          lastUpdated: res.data.article.lastUpdated || new Date(),
        }));
        setActionMessage(
          targetStatus === "Published"
            ? "Article is now LIVE on the public website!"
            : "Article moved to Draft (hidden from public)."
        );
      }
    } catch (err) {
      alert(err.response?.data?.message || "Failed to update article status");
    } finally {
      setStatusUpdating(false);
    }
  };

  if (loading) {
    return (
      <div className="min-h-[60vh] flex flex-col items-center justify-center space-y-3">
        <div className="h-8 w-8 animate-spin rounded-full border-3 border-blue-600 border-t-transparent" />
        <p className="text-xs font-semibold text-slate-500">Loading article preview...</p>
      </div>
    );
  }

  if (error || !article) {
    return (
      <div className="max-w-2xl mx-auto px-4 py-20 text-center space-y-4">
        <div className="p-4 rounded-2xl bg-red-50 border border-red-200 text-red-700 text-xs font-bold inline-block">
          ⚠️ {error || "Article not found"}
        </div>
        <div>
          <Link
            href="/admin/articles"
            className="px-4 py-2 bg-blue-600 text-white rounded-xl text-xs font-bold hover:bg-blue-700"
          >
            ← Back to Articles CMS
          </Link>
        </div>
      </div>
    );
  }

  const isPublished = article.status === "Published";

  return (
    <div className="min-h-screen bg-white">
      {/* STICKY ADMIN PREVIEW TOPBAR */}
      <aside aria-label="Admin Control Bar" className="sticky top-0 z-40 bg-slate-900 text-white px-4 py-3 border-b border-slate-800 shadow-md">
        <div className="max-w-7xl mx-auto flex flex-col sm:flex-row sm:items-center justify-between gap-3">
          <div className="flex items-center gap-2.5">
            <span className="text-sm font-extrabold uppercase tracking-wider text-slate-400">
              Admin Preview
            </span>
            <span className="text-slate-600">|</span>
            {isPublished ? (
              <span className="inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full text-[11px] font-bold bg-emerald-500/20 text-emerald-300 border border-emerald-500/30">
                <span className="h-1.5 w-1.5 rounded-full bg-emerald-400" />
                Live / Published
              </span>
            ) : (
              <span className="inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full text-[11px] font-bold bg-amber-500/20 text-amber-300 border border-amber-500/30">
                <span className="h-1.5 w-1.5 rounded-full bg-amber-400" />
                Draft Mode (Hidden from Public)
              </span>
            )}
            {article.isAutoGenerated && (
              <span className="text-[10px] bg-slate-800 text-teal-300 border border-teal-500/30 px-2 py-0.5 rounded-md font-semibold">
                Auto-Crawled
              </span>
            )}
          </div>

          <div className="flex flex-wrap items-center gap-2">
            <Link
              href="/admin/articles"
              className="px-3 py-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-semibold transition"
            >
              ← Back to CMS
            </Link>

            <Link
              href={`/admin/articles/edit/${article._id}`}
              className="px-3 py-1.5 rounded-lg bg-indigo-600 hover:bg-indigo-700 text-white text-xs font-semibold transition"
            >
              Edit Article ✎
            </Link>

            {isPublished ? (
              <>
                <Link
                  href={`/news/${article.slug}`}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="px-3 py-1.5 rounded-lg bg-blue-600 hover:bg-blue-700 text-white text-xs font-bold transition"
                >
                  View Public URL ↗
                </Link>
                <button
                  onClick={() => handleToggleStatus("Draft")}
                  disabled={statusUpdating}
                  className="px-3 py-1.5 rounded-lg bg-amber-600 hover:bg-amber-700 text-white text-xs font-bold transition disabled:opacity-50 cursor-pointer"
                >
                  {statusUpdating ? "Updating..." : "Move to Draft"}
                </button>
              </>
            ) : (
              <button
                onClick={() => handleToggleStatus("Published")}
                disabled={statusUpdating}
                className="px-4 py-1.5 rounded-lg bg-gradient-to-r from-emerald-500 to-teal-500 hover:from-emerald-600 hover:to-teal-600 text-white text-xs font-extrabold shadow-sm transition disabled:opacity-50 cursor-pointer"
              >
                {statusUpdating ? "Publishing..." : "🚀 Make Live (Publish)"}
              </button>
            )}
          </div>
        </div>

        {actionMessage && (
          <div className="max-w-7xl mx-auto mt-2 pt-2 border-t border-slate-800 text-xs font-semibold text-emerald-400">
            ✓ {actionMessage}
          </div>
        )}
      </aside>

      {/* ARTICLE HERO HEADER */}
      <header className="border-b border-slate-200 bg-slate-50/60 py-8 px-4 sm:px-6 lg:px-8">
        <div className="mx-auto max-w-4xl">
          {/* Breadcrumbs */}
          <nav aria-label="Breadcrumb" className="text-xs font-semibold text-slate-500 mb-4">
            <ol className="flex flex-wrap items-center gap-1.5">
              <li>
                <Link href="/" className="hover:text-blue-600 transition">
                  Home
                </Link>
              </li>
              <li className="text-slate-400">/</li>
              <li>
                <Link href="/news" className="hover:text-blue-600 transition">
                  Exam Updates
                </Link>
              </li>
              <li className="text-slate-400">/</li>
              <li>
                <span className="text-blue-600">{article.category}</span>
              </li>
              <li className="text-slate-400">/</li>
              <li className="text-slate-800 line-clamp-1 max-w-xs">{article.shortTitle}</li>
            </ol>
          </nav>

          {/* Badges */}
          <div className="flex flex-wrap items-center gap-2 mb-3">
            <span className="px-3 py-1 rounded-full text-xs font-bold bg-blue-50 text-blue-700 border border-blue-200">
              {article.category}
            </span>
            <span className="px-3 py-1 rounded-full text-xs font-bold bg-emerald-50 text-emerald-700 border border-emerald-200 flex items-center gap-1.5">
              <span className="h-2 w-2 rounded-full bg-emerald-500" />
              {article.badge}
            </span>
            {article.advtNumber && (
              <span className="text-xs font-medium text-slate-500 bg-slate-100 px-2.5 py-0.5 rounded-full">
                Advt. No: {article.advtNumber}
              </span>
            )}
          </div>

          {/* H1 Title */}
          <h1 className="text-2xl sm:text-3xl lg:text-4xl font-extrabold text-slate-900 tracking-tight leading-tight">
            {article.title}
          </h1>

          {/* Author Byline & Timestamp */}
          <div className="mt-4 flex flex-wrap items-center justify-between gap-4 pt-4 border-t border-slate-200 text-xs text-slate-500">
            <div className="flex items-center gap-2.5">
              <div className="h-8 w-8 rounded-full bg-blue-600 text-white font-bold flex items-center justify-center text-xs shadow-2xs">
                PP
              </div>
              <div>
                <span className="font-bold text-slate-800 block leading-tight">
                  {article.author?.name || "Prayaas Karo Exam Desk"}
                </span>
                <span className="text-slate-500 text-[11px]">
                  {article.author?.role || "Senior Exam Analyst"}
                </span>
              </div>
            </div>

            <div className="flex flex-col sm:flex-row sm:items-center gap-2 sm:gap-3 text-[11px] sm:text-xs">
              <div className="flex items-center gap-1.5 bg-slate-100 px-2.5 py-1 rounded-md text-slate-700">
                <span className="font-medium text-slate-500">Status:</span>
                <span className={`font-bold ${isPublished ? "text-emerald-700" : "text-amber-700"}`}>
                  {article.status}
                </span>
              </div>
              <div className="flex items-center gap-1.5 bg-slate-100 px-2.5 py-1 rounded-md text-slate-700">
                <span className="font-medium text-slate-500">Reading Time:</span>
                <span className="font-bold text-slate-900">{article.readingTime || "4 min read"}</span>
              </div>
            </div>
          </div>
        </div>
      </header>

      {/* ARTICLE CLIENT CONTENT */}
      <ArticleClient article={article} />
    </div>
  );
}
